### ISSUE TITLE
rename `*-accessor` => `*-key`

### ISSUE THREAD

**Issue by ghost** [LocusEnergy/ember-sparkles#24]
we use things like `inputAccessor`, `outputAccessor`, `groupAccessor` in a few places - `inputKey`, `outputKey`, `groupKey` is a bit less awkward to say as well as shorter :-)

**Comment by ghost** [comment]
this also follows the naming convention within D3

**Comment by ghost** [comment]
@taras what do you think about this?

**Comment by taras** [comment]
I'm for it! 👍
