### ISSUE TITLE
Example of bar chart doesn't work

### ISSUE THREAD

**Issue by yarigpopov** [LocusEnergy/ember-sparkles#37]
Hi!

I tried to run an example of bar chart, but failed. 

I'm getting an error `Assertion Failed: r/get expects argument to be not be undefined`
which occurs when the value of `inputKey` in [this line](https://github.com/LocusEnergy/ember-sparkles/blob/399157909ed44954bff1b0cb4b9ff564b7319833/addon/templates/components/ember-sparkles.hbs#L16) is calculated with `read` function of `ember-htmlbars/streams/utils`

```
  function read(object) {
    if (object && object[_emberHtmlbarsStreamsStream.IS_STREAM]) {
      return object.value();
    } else {
      return object;
    }
  }
```

`object.value()` returns `undefined` from `[Child]` array. 

**here I put a [repo](https://github.com/chilicoder/ember-sparkles-example) with the code.** I used chrome 52 in macOS and `2.7.2`version of Ember.
<img width="575" alt="screen shot 2016-09-01 at 16 24 34" src="https://cloud.githubusercontent.com/assets/3491833/18171012/b6fdd508-7060-11e6-8b04-395ceb92dffa.png">

Could you please help to resolve the issue?

**Comment by ghost** [comment]
@chilicoder thanks for trying this out and catching this! the documentation had been updated but I forgot to publish a new version - upgrade to ember-sparkles v0.4.12 in package.json and this should work for you (I just tested with your repo on my machine). Please let us me know if you run into any problems, and good luck!

**Comment by ghost** [comment]
closing this until further notice – please feel free to comment / reopen if this issue isn't resolved for you.

**Comment by yarigpopov** [comment]
Thanks! Now it works!
