### ISSUE TITLE
v0.4.15 doesn't work with Ember v2.10.0

### ISSUE THREAD

**Issue by yarigpopov** [LocusEnergy/ember-sparkles#55]
Hi! I'm trying new version but fail to run the app.
here is the issue
<img width="1085" alt="screen shot 2016-12-05 at 13 18 58" src="https://cloud.githubusercontent.com/assets/3491833/20884920/526a5b92-baee-11e6-88a0-64e0518d4970.png">

I made a repo for example
https://github.com/chilicoder/ember-sparkles-example2

looks like something with ember-let dependency.. but installing it doesn't help

**Comment by yarigpopov** [comment]
I could make it work after downgrading
to Ember v 2.9.0 
and adding dependency
```
"ember-let": "^0.4.0",
```

**Comment by yarigpopov** [comment]
I created a discussion on ember forum
http://discuss.emberjs.com/t/migrating-ember-sparkles-from-2-9-1-to-2-10-d3-chart-library/12091/2

**Comment by jdurand** [comment]
@chilicoder from your first error message it seems you’re missing `ember-let` have you tried `ember install ember-let`?

**Comment by ghost** [comment]
this has been fixed in the latest release, 0.4.16
