### ISSUE TITLE
Is this project deprecated?

### ISSUE THREAD

**Issue by yarigpopov** [LocusEnergy/ember-sparkles#57]
Can you please share some information what happened with maintainers? The priorities changed? Some big impediments raised? Or anything else?

I liked the approach of this project a lot, but seems like no activities for last several months.  I could manage to create stacked bar charts, add labels and some other customization. I see that approach works, although it has a bit steep learning curve in the beginning. 

As an improvement, it would be nice to move all charts definitions out of `ember-sparkles` component and instead yield options. This will increase compostability and allow to use custom charts outside of the project (for now I have to rewrite template `ember-sparkles.hbs`)

Anyways, I would like to hear some news from maintainers

**Comment by ghost** [comment]
Hi, thanks for your interest and questions. This project isn't deprecated, but we've been busy with some other projects, unfortunately. 

I did just finally figure out how to upgrade this project to Ember 2.10, which was a big step - this will address #55. I have a PR pending.

We think this project has a lot of potential - the next big thing would be to add more user interactivity, like you asked about in #50 and also mentioned in #40. We welcome any assistance, so if you'd like to help out with these please let me know! We will need to add some helpers to the ember-d3-helpers addon.

I like your idea for yielding options out of the ember-sparkles component, would you be up for sharing what your rewritten `ember-sparkles.hbs` looks like? I'd like to understand how this is helping you.

**Comment by yarigpopov** [comment]
Hi @zigahertz 
Here I created a branch to show the idea
https://github.com/LocusEnergy/ember-sparkles/compare/master...chilicoder:composable-chart
